/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 2
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_set = 1,
  sym_option = 2,
  sym__int = 3,
  anon_sym_DOT = 4,
  anon_sym_true = 5,
  anon_sym_false = 6,
  sym__word = 7,
  anon_sym_SQUOTE = 8,
  aux_sym__string_token1 = 9,
  anon_sym_DQUOTE = 10,
  aux_sym__string_token2 = 11,
  anon_sym_include = 12,
  anon_sym_unmap = 13,
  anon_sym_map = 14,
  aux_sym_map_directive_token1 = 15,
  anon_sym_LT = 16,
  aux_sym_key_token1 = 17,
  anon_sym_GT = 18,
  aux_sym_key_token2 = 19,
  aux_sym_key_token3 = 20,
  anon_sym_LBRACK = 21,
  aux_sym_mode_token1 = 22,
  anon_sym_RBRACK = 23,
  anon_sym_POUND = 24,
  aux_sym_comment_token1 = 25,
  aux_sym_comment_token2 = 26,
  sym__terminator = 27,
  sym_file = 28,
  sym__statements = 29,
  sym__statement = 30,
  sym_set_directive = 31,
  sym_int = 32,
  sym_float = 33,
  sym_bool = 34,
  sym__string = 35,
  sym__argument = 36,
  sym_include_directive = 37,
  sym_unmap_directive = 38,
  sym_map_directive = 39,
  sym_key = 40,
  sym_mode = 41,
  sym_comment = 42,
  aux_sym__statements_repeat1 = 43,
  alias_sym_argument = 44,
  alias_sym_path = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_set] = "command",
  [sym_option] = "option",
  [sym__int] = "_int",
  [anon_sym_DOT] = ".",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym__word] = "string",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__string_token1] = "string",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__string_token2] = "string",
  [anon_sym_include] = "command",
  [anon_sym_unmap] = "command",
  [anon_sym_map] = "command",
  [aux_sym_map_directive_token1] = "function",
  [anon_sym_LT] = "<",
  [aux_sym_key_token1] = "key_name",
  [anon_sym_GT] = ">",
  [aux_sym_key_token2] = "key_token2",
  [aux_sym_key_token3] = "key_token3",
  [anon_sym_LBRACK] = "[",
  [aux_sym_mode_token1] = "mode_name",
  [anon_sym_RBRACK] = "]",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "body",
  [sym__terminator] = "_terminator",
  [sym_file] = "file",
  [sym__statements] = "_statements",
  [sym__statement] = "_statement",
  [sym_set_directive] = "set_directive",
  [sym_int] = "int",
  [sym_float] = "float",
  [sym_bool] = "bool",
  [sym__string] = "_string",
  [sym__argument] = "_argument",
  [sym_include_directive] = "include_directive",
  [sym_unmap_directive] = "unmap_directive",
  [sym_map_directive] = "map_directive",
  [sym_key] = "key",
  [sym_mode] = "mode",
  [sym_comment] = "comment",
  [aux_sym__statements_repeat1] = "_statements_repeat1",
  [alias_sym_argument] = "argument",
  [alias_sym_path] = "path",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_set] = anon_sym_set,
  [sym_option] = sym_option,
  [sym__int] = sym__int,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym__word] = sym__word,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__string_token1] = sym__word,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__string_token2] = sym__word,
  [anon_sym_include] = anon_sym_set,
  [anon_sym_unmap] = anon_sym_set,
  [anon_sym_map] = anon_sym_set,
  [aux_sym_map_directive_token1] = aux_sym_map_directive_token1,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_key_token1] = aux_sym_key_token1,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_key_token2] = aux_sym_key_token2,
  [aux_sym_key_token3] = aux_sym_key_token3,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_mode_token1] = aux_sym_mode_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [sym__terminator] = sym__terminator,
  [sym_file] = sym_file,
  [sym__statements] = sym__statements,
  [sym__statement] = sym__statement,
  [sym_set_directive] = sym_set_directive,
  [sym_int] = sym_int,
  [sym_float] = sym_float,
  [sym_bool] = sym_bool,
  [sym__string] = sym__string,
  [sym__argument] = sym__argument,
  [sym_include_directive] = sym_include_directive,
  [sym_unmap_directive] = sym_unmap_directive,
  [sym_map_directive] = sym_map_directive,
  [sym_key] = sym_key,
  [sym_mode] = sym_mode,
  [sym_comment] = sym_comment,
  [aux_sym__statements_repeat1] = aux_sym__statements_repeat1,
  [alias_sym_argument] = alias_sym_argument,
  [alias_sym_path] = alias_sym_path,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym__word] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__string_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_unmap] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_map_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_key_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_key_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_key_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_mode_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = true,
    .named = true,
  },
  [sym__terminator] = {
    .visible = false,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statements] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_set_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym__string] = {
    .visible = false,
    .named = true,
  },
  [sym__argument] = {
    .visible = false,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_unmap_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_map_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__statements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_argument] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_path] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_content = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 1},
  [5] = {.index = 2, .length = 1},
  [6] = {.index = 3, .length = 1},
  [7] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 2, .inherited = true},
  [1] =
    {field_content, 3, .inherited = true},
  [2] =
    {field_content, 1},
  [3] =
    {field_content, 4, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_path,
  },
  [3] = {
    [0] = alias_sym_argument,
  },
  [7] = {
    [1] = alias_sym_argument,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 5,
  [11] = 11,
  [12] = 12,
  [13] = 6,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 14,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 40,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 37,
  [59] = 59,
  [60] = 31,
  [61] = 61,
  [62] = 62,
  [63] = 56,
  [64] = 62,
  [65] = 65,
  [66] = 41,
  [67] = 67,
  [68] = 68,
};

static const TSCharacterRange aux_sym_key_token3_character_set_1[] = {
  {0, '\t'}, {0x0b, 0x1f}, {'!', ';'}, {'=', '='}, {'?', 'Z'}, {'\\', '\\'}, {'^', 0x17e}, {0x180, 0x2129},
  {0x212b, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      if (lookahead == '"') ADVANCE(72);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '<') ADVANCE(82);
      if (lookahead == '>') ADVANCE(84);
      if (lookahead == '[') ADVANCE(90);
      if (lookahead == '\\') SKIP(38);
      if (lookahead == ']') ADVANCE(95);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 'm') ADVANCE(13);
      if (lookahead == 's') ADVANCE(17);
      if (lookahead == 't') ADVANCE(28);
      if (lookahead == 'u') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(6);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(7);
      END_STATE();
    case 3:
      if (lookahead == '\r') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 4:
      if (lookahead == '\r') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(72);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '.') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(52);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 't') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\\') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\\') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '-' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\\') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(99);
      if (lookahead == '<') ADVANCE(82);
      if (lookahead == '[') ADVANCE(90);
      if (lookahead == '\\') ADVANCE(86);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(9);
      if (lookahead == '>' ||
          lookahead == ']') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(87);
      END_STATE();
    case 10:
      if (lookahead == '#') ADVANCE(99);
      if (lookahead == '<') ADVANCE(82);
      if (lookahead == '\\') ADVANCE(86);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(10);
      if (lookahead == '>' ||
          ('[' <= lookahead && lookahead <= ']')) ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(87);
      END_STATE();
    case 11:
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '\\') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(80);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(79);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 33:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 34:
      if (eof) ADVANCE(40);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 35:
      if (eof) ADVANCE(40);
      if (lookahead == '\n') ADVANCE(106);
      if (lookahead == '"') ADVANCE(72);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 36:
      if (eof) ADVANCE(40);
      if (lookahead == '\n') SKIP(37);
      END_STATE();
    case 37:
      if (eof) ADVANCE(40);
      if (lookahead == '\n') ADVANCE(107);
      if (lookahead == '#') ADVANCE(96);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '\\') SKIP(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 38:
      if (eof) ADVANCE(40);
      if (lookahead == '\r') SKIP(34);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      if (lookahead == '\r') SKIP(36);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(37);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_option);
      if (lookahead == '-' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__int);
      if (lookahead == '\\') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\n') ADVANCE(106);
      if (lookahead == '\\') ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\r') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\r') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\r') ADVANCE(63);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '.') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(52);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 't') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == 'l') ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == 'r') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == 's') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead == 'u') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\\') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(63);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym__string_token1);
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym__string_token1);
      if (lookahead == '\r') ADVANCE(67);
      if (lookahead == '\\') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym__string_token1);
      if (lookahead == '#') ADVANCE(97);
      if (lookahead == '\\') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym__string_token1);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym__string_token1);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym__string_token2);
      if (lookahead == '\n') ADVANCE(75);
      if (lookahead == '\\') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym__string_token2);
      if (lookahead == '\r') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__string_token2);
      if (lookahead == '#') ADVANCE(98);
      if (lookahead == '\\') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym__string_token2);
      if (lookahead == '\\') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym__string_token2);
      if (lookahead == '\\') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_unmap);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_map_directive_token1);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_key_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_key_token2);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_key_token2);
      if (lookahead == '\r') ADVANCE(89);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(88);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_key_token2);
      if ((!eof && set_contains(aux_sym_key_token3_character_set_1, 9, lookahead))) ADVANCE(89);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_key_token3);
      if (lookahead == '#') ADVANCE(99);
      if (lookahead == '\\') ADVANCE(86);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(88);
      if ((!eof && set_contains(aux_sym_key_token3_character_set_1, 9, lookahead))) ADVANCE(87);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_key_token3);
      if ((!eof && set_contains(aux_sym_key_token3_character_set_1, 9, lookahead))) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_mode_token1);
      if (lookahead == '\n') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_mode_token1);
      if (lookahead == '\r') ADVANCE(91);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_mode_token1);
      if (lookahead == '#') ADVANCE(101);
      if (lookahead == '\\') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_mode_token1);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(70);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '\\') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(76);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_POUND);
      if ((!eof && set_contains(aux_sym_key_token3_character_set_1, 9, lookahead))) ADVANCE(89);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(105);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(94);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\r') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(105);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '#') ADVANCE(100);
      if (lookahead == '\\') ADVANCE(103);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym__terminator);
      if (lookahead == '\n') ADVANCE(106);
      if (lookahead == '\\') ADVANCE(53);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__terminator);
      if (lookahead == '\n') ADVANCE(107);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 35},
  [6] = {.lex_state = 35},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 35},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 35},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 37},
  [19] = {.lex_state = 37},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 37},
  [22] = {.lex_state = 37},
  [23] = {.lex_state = 37},
  [24] = {.lex_state = 37},
  [25] = {.lex_state = 37},
  [26] = {.lex_state = 37},
  [27] = {.lex_state = 37},
  [28] = {.lex_state = 37},
  [29] = {.lex_state = 37},
  [30] = {.lex_state = 37},
  [31] = {.lex_state = 37},
  [32] = {.lex_state = 37},
  [33] = {.lex_state = 37},
  [34] = {.lex_state = 37},
  [35] = {.lex_state = 37},
  [36] = {.lex_state = 37},
  [37] = {.lex_state = 37},
  [38] = {.lex_state = 37},
  [39] = {.lex_state = 37},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 69},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 69},
  [49] = {.lex_state = 75},
  [50] = {.lex_state = 102},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 75},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 104},
  [60] = {.lex_state = 6},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 37},
  [68] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [sym__int] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_unmap] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [aux_sym_key_token1] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_file] = STATE(61),
    [sym__statements] = STATE(65),
    [sym__statement] = STATE(24),
    [sym_set_directive] = STATE(26),
    [sym_include_directive] = STATE(26),
    [sym_unmap_directive] = STATE(26),
    [sym_map_directive] = STATE(26),
    [sym_comment] = STATE(1),
    [aux_sym__statements_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_set] = ACTIONS(7),
    [anon_sym_include] = ACTIONS(9),
    [anon_sym_unmap] = ACTIONS(11),
    [anon_sym_map] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(15), 1,
      sym__int,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      sym__word,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(2), 1,
      sym_comment,
    STATE(27), 1,
      sym__string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(23), 3,
      sym_int,
      sym_float,
      sym_bool,
  [34] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(29), 1,
      anon_sym_set,
    ACTIONS(32), 1,
      anon_sym_include,
    ACTIONS(35), 1,
      anon_sym_unmap,
    ACTIONS(38), 1,
      anon_sym_map,
    STATE(67), 1,
      sym__statement,
    STATE(3), 2,
      sym_comment,
      aux_sym__statements_repeat1,
    STATE(26), 4,
      sym_set_directive,
      sym_include_directive,
      sym_unmap_directive,
      sym_map_directive,
  [63] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_set,
    ACTIONS(9), 1,
      anon_sym_include,
    ACTIONS(11), 1,
      anon_sym_unmap,
    ACTIONS(13), 1,
      anon_sym_map,
    STATE(3), 1,
      aux_sym__statements_repeat1,
    STATE(4), 1,
      sym_comment,
    STATE(21), 1,
      sym__statement,
    STATE(26), 4,
      sym_set_directive,
      sym_include_directive,
      sym_unmap_directive,
      sym_map_directive,
  [94] = 8,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      sym__word,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      sym__terminator,
    STATE(5), 1,
      sym_comment,
    STATE(30), 1,
      sym__argument,
  [119] = 8,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(43), 1,
      sym__word,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym__terminator,
    STATE(6), 1,
      sym_comment,
    STATE(35), 1,
      sym__argument,
  [144] = 7,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(55), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    STATE(7), 1,
      sym_comment,
    STATE(14), 1,
      sym_mode,
    STATE(53), 1,
      sym_key,
    ACTIONS(57), 2,
      aux_sym_key_token2,
      aux_sym_key_token3,
  [167] = 7,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_LT,
    STATE(8), 1,
      sym_comment,
    STATE(16), 1,
      sym_mode,
    STATE(39), 1,
      sym_key,
    ACTIONS(63), 2,
      aux_sym_key_token2,
      aux_sym_key_token3,
  [190] = 7,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(55), 1,
      anon_sym_LT,
    ACTIONS(59), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_comment,
    STATE(17), 1,
      sym_mode,
    STATE(40), 1,
      sym_key,
    ACTIONS(57), 2,
      aux_sym_key_token2,
      aux_sym_key_token3,
  [213] = 7,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(43), 1,
      sym__word,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(49), 1,
      sym__terminator,
    STATE(10), 1,
      sym_comment,
    STATE(30), 1,
      sym__argument,
  [235] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_comment,
    ACTIONS(67), 4,
      anon_sym_set,
      anon_sym_include,
      anon_sym_unmap,
      anon_sym_map,
  [251] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(12), 1,
      sym_comment,
    ACTIONS(67), 4,
      anon_sym_set,
      anon_sym_include,
      anon_sym_unmap,
      anon_sym_map,
  [267] = 7,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(43), 1,
      sym__word,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(47), 1,
      anon_sym_DQUOTE,
    ACTIONS(53), 1,
      sym__terminator,
    STATE(13), 1,
      sym_comment,
    STATE(35), 1,
      sym__argument,
  [289] = 5,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(55), 1,
      anon_sym_LT,
    STATE(14), 1,
      sym_comment,
    STATE(62), 1,
      sym_key,
    ACTIONS(57), 2,
      aux_sym_key_token2,
      aux_sym_key_token3,
  [306] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(15), 1,
      sym_comment,
    ACTIONS(67), 4,
      anon_sym_set,
      anon_sym_include,
      anon_sym_unmap,
      anon_sym_map,
  [319] = 5,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(61), 1,
      anon_sym_LT,
    STATE(16), 1,
      sym_comment,
    STATE(25), 1,
      sym_key,
    ACTIONS(63), 2,
      aux_sym_key_token2,
      aux_sym_key_token3,
  [336] = 5,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(55), 1,
      anon_sym_LT,
    STATE(17), 1,
      sym_comment,
    STATE(64), 1,
      sym_key,
    ACTIONS(57), 2,
      aux_sym_key_token2,
      aux_sym_key_token3,
  [353] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(73), 1,
      sym__int,
    STATE(18), 1,
      sym_comment,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [367] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(77), 1,
      anon_sym_DOT,
    STATE(19), 1,
      sym_comment,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [381] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(20), 1,
      sym_comment,
    ACTIONS(79), 3,
      anon_sym_LT,
      aux_sym_key_token2,
      aux_sym_key_token3,
  [393] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym__terminator,
    STATE(21), 1,
      sym_comment,
  [406] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_comment,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [417] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym_comment,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [428] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      sym__terminator,
    STATE(24), 1,
      sym_comment,
  [441] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym_comment,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [452] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [463] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [474] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [485] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(29), 1,
      sym_comment,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [496] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(30), 1,
      sym_comment,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [507] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(31), 1,
      sym_comment,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [518] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(32), 1,
      sym_comment,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [529] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(33), 1,
      sym_comment,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [540] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(34), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [551] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(35), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [562] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(36), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [573] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(37), 1,
      sym_comment,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [584] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(38), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [595] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    STATE(39), 1,
      sym_comment,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      sym__terminator,
  [606] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(119), 1,
      aux_sym_map_directive_token1,
    STATE(40), 1,
      sym_comment,
  [616] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(121), 1,
      aux_sym_key_token1,
    STATE(41), 1,
      sym_comment,
  [626] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(123), 1,
      aux_sym__string_token1,
    STATE(42), 1,
      sym_comment,
  [636] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    STATE(43), 1,
      sym_comment,
  [646] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(125), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      sym_comment,
  [656] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(127), 1,
      sym__word,
    STATE(45), 1,
      sym_comment,
  [666] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(129), 1,
      sym__int,
    STATE(46), 1,
      sym_comment,
  [676] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(131), 1,
      aux_sym_mode_token1,
    STATE(47), 1,
      sym_comment,
  [686] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(133), 1,
      aux_sym__string_token1,
    STATE(48), 1,
      sym_comment,
  [696] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(135), 1,
      aux_sym__string_token2,
    STATE(49), 1,
      sym_comment,
  [706] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(137), 1,
      aux_sym_comment_token1,
    STATE(50), 1,
      sym_comment,
  [716] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(139), 1,
      sym_option,
    STATE(51), 1,
      sym_comment,
  [726] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(141), 1,
      aux_sym__string_token2,
    STATE(52), 1,
      sym_comment,
  [736] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(143), 1,
      aux_sym_map_directive_token1,
    STATE(53), 1,
      sym_comment,
  [746] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      sym_comment,
  [756] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_comment,
  [766] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(147), 1,
      anon_sym_GT,
    STATE(56), 1,
      sym_comment,
  [776] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(149), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      sym_comment,
  [786] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(113), 1,
      aux_sym_map_directive_token1,
    STATE(58), 1,
      sym_comment,
  [796] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(151), 1,
      aux_sym_comment_token2,
    STATE(59), 1,
      sym_comment,
  [806] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      aux_sym_map_directive_token1,
    STATE(60), 1,
      sym_comment,
  [816] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_comment,
  [826] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(155), 1,
      aux_sym_map_directive_token1,
    STATE(62), 1,
      sym_comment,
  [836] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(157), 1,
      anon_sym_GT,
    STATE(63), 1,
      sym_comment,
  [846] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(159), 1,
      aux_sym_map_directive_token1,
    STATE(64), 1,
      sym_comment,
  [856] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(65), 1,
      sym_comment,
  [866] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(163), 1,
      aux_sym_key_token1,
    STATE(66), 1,
      sym_comment,
  [876] = 3,
    ACTIONS(27), 1,
      anon_sym_POUND,
    ACTIONS(165), 1,
      sym__terminator,
    STATE(67), 1,
      sym_comment,
  [886] = 1,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 63,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 167,
  [SMALL_STATE(9)] = 190,
  [SMALL_STATE(10)] = 213,
  [SMALL_STATE(11)] = 235,
  [SMALL_STATE(12)] = 251,
  [SMALL_STATE(13)] = 267,
  [SMALL_STATE(14)] = 289,
  [SMALL_STATE(15)] = 306,
  [SMALL_STATE(16)] = 319,
  [SMALL_STATE(17)] = 336,
  [SMALL_STATE(18)] = 353,
  [SMALL_STATE(19)] = 367,
  [SMALL_STATE(20)] = 381,
  [SMALL_STATE(21)] = 393,
  [SMALL_STATE(22)] = 406,
  [SMALL_STATE(23)] = 417,
  [SMALL_STATE(24)] = 428,
  [SMALL_STATE(25)] = 441,
  [SMALL_STATE(26)] = 452,
  [SMALL_STATE(27)] = 463,
  [SMALL_STATE(28)] = 474,
  [SMALL_STATE(29)] = 485,
  [SMALL_STATE(30)] = 496,
  [SMALL_STATE(31)] = 507,
  [SMALL_STATE(32)] = 518,
  [SMALL_STATE(33)] = 529,
  [SMALL_STATE(34)] = 540,
  [SMALL_STATE(35)] = 551,
  [SMALL_STATE(36)] = 562,
  [SMALL_STATE(37)] = 573,
  [SMALL_STATE(38)] = 584,
  [SMALL_STATE(39)] = 595,
  [SMALL_STATE(40)] = 606,
  [SMALL_STATE(41)] = 616,
  [SMALL_STATE(42)] = 626,
  [SMALL_STATE(43)] = 636,
  [SMALL_STATE(44)] = 646,
  [SMALL_STATE(45)] = 656,
  [SMALL_STATE(46)] = 666,
  [SMALL_STATE(47)] = 676,
  [SMALL_STATE(48)] = 686,
  [SMALL_STATE(49)] = 696,
  [SMALL_STATE(50)] = 706,
  [SMALL_STATE(51)] = 716,
  [SMALL_STATE(52)] = 726,
  [SMALL_STATE(53)] = 736,
  [SMALL_STATE(54)] = 746,
  [SMALL_STATE(55)] = 756,
  [SMALL_STATE(56)] = 766,
  [SMALL_STATE(57)] = 776,
  [SMALL_STATE(58)] = 786,
  [SMALL_STATE(59)] = 796,
  [SMALL_STATE(60)] = 806,
  [SMALL_STATE(61)] = 816,
  [SMALL_STATE(62)] = 826,
  [SMALL_STATE(63)] = 836,
  [SMALL_STATE(64)] = 846,
  [SMALL_STATE(65)] = 856,
  [SMALL_STATE(66)] = 866,
  [SMALL_STATE(67)] = 876,
  [SMALL_STATE(68)] = 886,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_directive, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map_directive, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_directive, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map_directive, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statements_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mode, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_directive, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statements, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unmap_directive, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_directive, 3, 0, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_directive, 4, 0, 4),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 1, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__string, 3, 0, 5),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_directive, 5, 0, 6),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__argument, 3, 0, 7),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 2, 0, 1),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unmap_directive, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [153] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zathurarc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zathurarc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 4,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
